name: ESLint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint and its plugins
        run: |
          npm install --save-dev globals eslint-formatter-gha eslint-plugin-jsdoc @eslint/json @eslint/js @stylistic/eslint-plugin-js

      - name: Run ESLint
        run: npx eslint . -f gha

  suggest-fixes:
    name: Suggest ESLint fixes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint
        run: npm install --save-dev globals eslint-formatter-gha eslint-plugin-jsdoc @eslint/json @eslint/js @stylistic/eslint-plugin-js

      - name: Fix ESLint issues
        run: npx eslint . --fix

      - name: Suggest fixes
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: eslint
      - name: Install ESLint and GHA Formatter
        run: |
          npm install --save-dev globals eslint-formatter-gha eslint-plugin-jsdoc @eslint/json @eslint/js

      - name: Run ESLint with GHA Formatter
        run: npx eslint . -f gha
